warning_threshold: 15

excluded:
- Pods
- R.generated.swift
- LocalPods/TinkoffAuth/TinkoffAuth/Classes/R.generated.swift
- LocalPods/TinkoffNetwork/TinkoffNetwork/Classes/R.generated.swift
- LocalPods/TinkoffTickets/TinkoffTickets/Classes/R.generated.swift
- LocalPods/TinkoffAuth/Example
- LocalPods/TinkoffNetwork/Example
- LocalPods/TinkoffTickets/Example

disabled_rules:
- trailing_whitespace

line_length:
    warning: 150

function_parameter_count:
    warning: 10
    error: 15

file_length:
    warning: 500

type_body_length:
    warning: 400
    error: 450
